name: ghanaumc_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_messaging: ^15.2.2
  firebase_analytics: ^11.4.2
  firebase_crashlytics: ^4.3.2
  firebase_performance: ^0.10.1+2
  firebase_dynamic_links: ^6.1.2
  

    # Media packages
  image_picker: ^1.1.2
  file_picker: ^8.3.5
  video_player: ^2.5.2
  just_audio: ^0.9.26
  
  share_plus: ^7.2.1 

 # Other typical dependencies
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/church_logo.jpg
   